Displayed Category of Scones
plt-amy/1lab pull request #148
Opened 2022-10-23 17:38 UTC by TOTBWF

# Description

This PR adds the displayed category of scones, and also proves that change of base of a fibration yields a fibration.

## Notes

The motivation for the category of scones could be a lot better! Ideally we'd prove canonicity of STLC using it, but I have too many WIP branches rn, so l'll circle back to it at a later date :)

2022-10-23 18:12 UTC, plt-amy requested changes

2022-10-23 18:12 UTC, plt-amy commented on src/Cat/Displayed/Instances/Scone.lagda.md
> +of $\ca{B}$.
I think this should read something like:

> [Pull back] the [fundamental fibration] of Sets along the global sections functor of B, to a fibration over B

Aiui the situation is
![](https://ame.fyi/9g6i.png)
where the two vertical arrows are fibrations?

2022-10-23 18:12 UTC, plt-amy commented on src/Cat/Displayed/Instances/Scone.lagda.md
> +of $\ca{B}$.
```latex
\[\begin{tikzcd}
  {\mathrm{Scn}(\mathcal{B})} && {\mathrm{Arr}(\mathbf{Sets})} \\
  \\
  {\mathcal{B}} && {\mathbf{Sets}}
  \arrow["{\mathrm{Slices}(\mathbf{Sets})}", from=1-3, to=3-3]
  \arrow["{\mathcal{B}(*,-)}"', from=3-1, to=3-3]
  \arrow[lies over, dashed, from=1-1, to=3-1]
  \arrow[lies over, from=1-1, to=1-3]
  \arrow["\lrcorner"{anchor=center, pos=0.125}, draw=none, from=1-1, to=3-3]
\end{tikzcd}\]
```
if you want to include the diagram

2022-10-23 18:12 UTC, plt-amy commented on src/Cat/Displayed/Instances/Scone.lagda.md
> +            → Scones.Hom[ f ] (scone U su) (scone V sv)
Align the arrows with the `:`, not the `∀`:
```suggestion
scone-hom : ∀ {X Y} {f : Hom X Y} {U V : Set ℓ}
          → {su : ∣ U ∣ → Hom top X} {sv : ∣ V ∣ → Hom top Y}
          → (uv : ∣ U ∣ → ∣ V ∣)
          → (∀ u → f ∘ (su u) ≡ sv (uv u))
          → Scones.Hom[ f ] (scone U su) (scone V sv)
```

2022-10-23 18:12 UTC, plt-amy commented on src/Cat/Displayed/Instances/Scone.lagda.md
> +the base category has pullbacks, which sets has!
```suggestion
the base category has pullbacks, which $\sets$ [has]!

[has]: Cat.Instances.Sets.Complete.html#finite-set-limits
```

2022-10-23 18:12 UTC, plt-amy commented on src/Cat/Displayed/Univalence/Thin.lagda.md
> +-->
lol thanks

2022-10-23 18:28 UTC, TOTBWF commented on src/Cat/Displayed/Univalence/Thin.lagda.md
> +-->
No worries haha

2022-10-24 00:45 UTC, TOTBWF commented
Not totally sure why this is failing? I can't find the missing link it's referring to in `Proposition.Resizing`

2022-10-24 07:02 UTC, merged