Opfibrations
plt-amy/1lab pull request #179
Opened 2023-01-27 00:24 UTC by TOTBWF

# Description

This PR is a bit beefy, so it's best to think of it in chunks. First, it proves a bunch of duality properties of morphism classes (IE: monos in `C^op` are epis in `C`, etc). Next, it defines the total opposite category, and proves duality properties for *displayed* morphism classes. Finally, it defines cocartesian maps and opfibrations, and proves a bunch of properties about them, mostly using duality arguments.

2023-01-28 04:33 UTC, plt-amy requested changes

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +"pushout diagram", in contrast to the cartesian maps "pullback diagrams".
Should this be "cartesian maps, which are ..."? Or "cartesian maps' ..."?

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +```
I feel like this whole section could be omitted from the website instead...

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +in the total opposite of $\ca{E}$ are cocartesian maps, and vice versa.
Link to [total opposite]?

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +</summary>
Can you like.. pull the type signatures out of the `<details>` block, having this explanation in a stand-alone paragraph?

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +```agda
Needs a line break here

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +referred to as opfibrations).
```suggestion
We can use this notion to define cocartesian fibrations (sometimes
referred to as **opfibrations**).
```

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Weak.lagda.md
> +<details>
This is an opening tag!

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Weak.lagda.md
> +<details>
This is also an opening tag!

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Weak.lagda.md
> +## Properties
I would remove the section break between these.. and pull out the type signatures to outside the `<details>` block

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Weak.lagda.md
> +	\arrow[lies over, from=1-5, to=3-5]
Could this be two spaces?

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Weak.lagda.md
> +</summary>
Add a blank line here, ditto for lifting the type signatures

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Weak.lagda.md
> +~~~{.quiver}
I think all the diagrams in this page could benefit from being

```
~~~{.quiver .tall-2}
```

+ replace the hard tabs for two spaces

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Instances/Family.lagda.md
> +point-wise isomorphisms. Showing the forward direction is a matter of
```suggestion
pointwise isomorphisms. Showing the forward direction is a matter of
```

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Morphism.lagda.md
> +record _↪[_]ʷ_
I'm starting to hate these names. Thoughts on `weak-mono-over`?

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Morphism.lagda.md
> +make-vert-iso
```suggestion
make-vertical-iso
```

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Morphism/Duality.lagda.md
> +monic[]^op→epic[] f .Cat.Displayed.Morphism.mor′ =
Definitely open all of these records so you don't have to repeat the module name in the copattern

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Reasoning.lagda.md
> +cast[]
```suggestion

cast[]
```

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Reasoning.lagda.md
> +cast[]
(if the suggestion is wonky, I mean "put them in the same code block")

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Total/Op.lagda.md
> +displayed category over $\ca{B}^{op}$; we call this category the
```suggestion
displayed category over $\ca{B}\op$; we call this category the
```

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Morphism/Duality.lagda.md
> +case, just mountains of boilerplate.
Make "non-displayed case" a link?

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cartesian.lagda.md
> +by a category, should be a _pseudofunctor_ $\ca{B}^{op} \to \Cat$, where
```suggestion
by a category, should be a _pseudofunctor_ $\ca{B}\op \to \Cat$, where
```

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +```agda
So to fit this should be called `is-cocartesian`, same for `is-cartesian` in the other module. Thoughts?

2023-01-28 04:33 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian.lagda.md
> +cartesian^op→cocartesian
To fit with Cat.Diagram.Duals this should be called `co-cartesian→cocartesian`

2023-01-28 18:21 UTC, TOTBWF commented on src/Cat/Displayed/Cocartesian.lagda.md
> +```agda
Agreed. It also removes a conflict from `Cat.Diagram.Product`, so easy win1

2023-01-29 00:18 UTC, plt-amy approved these changes

2023-01-29 00:19 UTC, merged