Bifibrations
plt-amy/1lab pull request #184
Opened 2023-02-01 07:32 UTC by TOTBWF

# Description

This PR defines bifibrations, and characterizes them as cartesian fibrations with left adjoints to base change.
Doing so cleanly requires a minor refactor of some properties of weak cartesian morphisms, along with some new
definitions:
* Displayed hom categories
* Opreindexing for opfibrations

This PR also adds the (start) of a natural isomorphism API; we should improve this in the future!

## Notes
I couldn't come up with a better name for `push-out`. Suggestions would be appreciated!

2023-02-01 18:07 UTC, plt-amy commented on src/Cat/Displayed/Bifibration.lagda.md
> +to reindexing functors. To see this, note that we need to construct
```suggestion
If $\cE$ is a bifibration, then its opreindexing functors are [left adjoints]
to its reindexing functors. To see this, note that we need to construct
```

again, maybe?

2023-02-01 18:42 UTC, plt-amy commented on src/Cat/Displayed/Cartesian/Indexing.lagda.md
> +    mi .eta x =
Oh my god thank you so much

2023-02-01 18:43 UTC, plt-amy commented on src/Cat/Displayed/Cartesian/Weak.lagda.md
> +    universalv g′
Can you open `is-weak-cartesian` and unqualify the copatterns?

2023-02-01 18:43 UTC, plt-amy commented on src/Cat/Displayed/Cartesian/Weak.lagda.md
> +postcompose-equiv→weak-cartesian f′ eqv .is-weak-cartesian.universal h′ =
ditto re copattern qualification here

2023-02-01 18:44 UTC, plt-amy commented on src/Cat/Displayed/Cartesian/Weak.lagda.md
> +weak-fibration→fibration weak-fib weak-∘ .Cartesian-fibration.has-lift {x = x} f y′ = f-lift where
open `Cartesian-fibration`; this line is very long otherwise

2023-02-01 21:51 UTC, plt-amy requested changes

2023-02-01 21:51 UTC, plt-amy commented on src/Cat/Displayed/Cartesian/Weak.lagda.md
> +
```suggestion
```

2023-02-01 21:51 UTC, plt-amy commented on src/Cat/Displayed/Cartesian/Weak.lagda.md
> +already have a suite of tools for constructing natural equivalences of
```suggestion
already have a toolkit for constructing natural equivalences of
```

2023-02-01 21:51 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Indexing.lagda.md
> +[opfibrations] are dual to [fibrations], so they inherit the ability
```suggestion
[Opfibrations] are dual to [fibrations], so they inherit the ability
```

2023-02-01 21:51 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Indexing.lagda.md
> +This gives distinction opfibrations a distinct character. Reindexing in
What happened to this sentence?

2023-02-01 21:51 UTC, plt-amy commented on src/Cat/Displayed/Cocartesian/Indexing.lagda.md
> +push-out : ∀ {x y} (f : Hom x y) → Functor (Fibre ℰ x) (Fibre ℰ y)
Could also be called "cobase-change". I've seen the nLab say that classes of morphisms are closed under cobase change before.

2023-02-01 21:51 UTC, plt-amy commented on src/Cat/Functor/Hom.lagda.md
> +Hom-from = Hom[_,-]
Renaming this will be a pain but please open an issue so we don't forget

2023-02-01 21:52 UTC, plt-amy commented on src/Cat/Functor/Hom.lagda.md
> +Hom-from = Hom[_,-]
Actually, #185

2023-02-01 22:23 UTC, TOTBWF commented on src/Cat/Displayed/Cocartesian/Indexing.lagda.md
> +This gives distinction opfibrations a distinct character. Reindexing in
whoops

2023-02-02 22:24 UTC, ncfavier commented on src/Cat/Displayed/Instances/Slice.lagda.md
> +that do not lie in the image of $f$.
...and merging fibres of elements that are mapped to the same element of `X`. Maybe we can mention that this interprets dependent sums?

2023-02-24 04:47 UTC, plt-amy approved these changes

2023-02-24 05:00 UTC, merged