Redefine (co)limits in terms of kan extensions
plt-amy/1lab pull request #186
Opened 2023-02-02 02:05 UTC by TOTBWF

# Description

This PR refactors (co)limits to be defined in terms of kan extensions. The main motivation for doing so is to make preservation of limits less annoying to deal with; as it currently stands we need to define special functions for mapping cones, which makes life much harder.

## Notes

As noted on discord, representability does not work due to (annoying!) universe level issues.
This PR is also based off #184; I'll rebase when the time comes.

2023-02-03 18:08 UTC, TOTBWF commented
When we get to RAPL/LAPC, we should probably prove the more general form where adjoints preserve kan extensions

2023-02-04 20:39 UTC, TOTBWF commented
I can handle porting the limits/colimits to all be in terms of the abstract defn!

2023-02-24 04:44 UTC, plt-amy requested changes

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +-->A
A

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +appropriate left extension.
```suggestion
As mentioned, our definition is very abstract, meaning we can directly
re-use definitions and theorems about Kan extensions in the setting of
colimits. The trade-off is that while working with colimits _in general_
is easier, working with _specific_ colimits becomes more difficult, as
the data we actually care about has been obfuscated.

One particularly egregious failure is... actually constructing colimits.
The definition in terms of `Lan`{.Agda} hides the concrete data behind a
few abstractions, which would be very tedious to write out each time. To
work around this, we provide an auxiliary record type,
`make-is-colimit`{.Agda}, as an intermediate step in constructing left
extensions.
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +First, we require morphisms from the every value to the diagram to
```suggestion
First, we require morphisms from the every value of the diagram to
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +the coapex; we call this family $\phi$. Moreover, if $f : x \to y$ is
```suggestion
the coapex; taken as a family, we call it $\phi$. Moreover, if $f : x \to y$ is
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +IE: the $\psi$ family is actually natural.
```suggestion
a morphism in the "shape" category $\cJ$, we require $\psi y \circ Ff = \psi x$,
which encodes the relevant naturality.
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +of maps iwth this property; if $\epsilon_j : Fj \to x$ is another natural
```suggestion
of maps with this property; if $\eps_j : Fj \to x$ is another natural
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +family, then each $\epsilon_j$ factors through the coapex by a _unique_
```suggestion
family, then each $\eps_j$ factors through the coapex by a _unique_
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +for *un*making a colimit.
```suggestion
The concrete interface of `make-is-colimit`{.Agda} is also handy for
_consuming_ specific colimits. To enable this use case, we provide a
function which **un**makes a colimit.
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +unfortunately proof assistants: `is-colimit`{.Agda} asks for _the_
```suggestion
unfortunately, proof assistants: `is-colimit`{.Agda} asks for _the_
```

Unfortunately, proof assistants always have a comma!

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +# Uniqueness
This is an instance of uniqueness of Lan, nay? Can't we reuse that? `Cat.Functor.Kan.Unique`

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Cocone.lagda.md
> +to define colimits via a categorical gadget called a **cocone**.
```suggestion
As noted in the main page on [colimits], most introductory texts opt
to define colimits via categorical gadgets called **cocones**.
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Cocone.lagda.md
> +of cones:
```suggestion
of cocones:
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Cocone.lagda.md
> +injection maps commute.
This paragraph needs to be rewritten

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Cocone.lagda.md
> +be the [initial] object in the category of cocones over $F$.
```suggestion
A cocone over some diagram $F$ contains the same data as natural
transformation from $F$ to a constant functor. This means that they
capture all the structure of colimits, save for the universal property.
That too can be encoded, by asking that the cocone in question be
an [initial object].
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Cocone.lagda.md
> +data around.
I would honestly just mention this process is invertible and comment out the entire definition of `is-colimit→is-initial-cocone`

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +colimit for that diagram.
I'm not a big fan of the em dashes here

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +domain is _also_ a colimit of the diagram.
This should also be proved in more generality

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +# Uniqueness
All of this duplication really isn't making our case that working with the abstract definition is better..! We should have all of these lemmas for arbitrary `is-lan`, in a module about extensions.

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +  is-invertible→is-colimitp
This should also be proved in more generality

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +  natural-iso→is-colimitp
This should be also proved in more generality. Have a function that allows varying every argument of `is-lan` by a natural isomorphsim

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Coproduct/Indexed.lagda.md
> +    → is-lan !F (Disc-adjunct F) K eps
Isn't this `is-colimit`?

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Duals.lagda.md
> +  Colimit→Co-limit colim = to-limit (to-is-limit ml) where
Isn't this redundant with Cat.Functor.Kan.Duality? Win, though

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +and commutation conditions in a category. This is required to describe
```suggestion
and commutativity conditions in a category. This is required to describe
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +of said object, some commuting conditions, and a universal property
```suggestion
of said object, some commutativity conditions, and a universal property
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +of the category with no objects.
```suggestion
being defined over the empty diagram, the unique functor from
the category with no objects.
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +functor equipped with natural transformation $\eta$; that is, for
```suggestion
functor equipped with a natural transformation $\eta$; that is, for
```

Write out eta's type, too?

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +have a unique natural transformation $\sigma : K \to !x$ that factorises
```suggestion
have a unique natural transformation $\sigma : K \to !x$ that factors
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +$\tau$. This is a bit of a mouthful, so lets look at a diagram instead.
```suggestion
$\tau$. This is a bit of a mouthful, so let's look at a diagram instead.
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +they are [right kan extensions]. This allows for an extremely concise
```suggestion
they are [right Kan extensions]. This allows for an extremely concise
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +a right kan extension of $! : \cJ \to \top$ along $D$.
```suggestion
a right Kan extension of $! : \cJ \to \top$ along $D$.
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +[right kan extensions]: Cat.Functor.Kan.Right.html
```suggestion
[right Kan extensions]: Cat.Functor.Kan.Right.html
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +          σ′ .is-natural _ _ _ ∙ ap (C._∘ _) (sym (K .F-id))
This can go, right?

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +unfortunately proof assistants: `is-limit`{.Agda} asks for _the_
```suggestion
unfortunately, proof assistants: `is-limit`{.Agda} asks for _the_
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
> +# Uniqueness
Similar comments about duplication with Kan extension stuff for colimits also applies here

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Base.lagda.md
>  ## Creation of limits
Let's delete this before merging and open an issue to define it again.

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Equaliser.lagda.md
> +Limit→Equaliser : ∀ {a b} {f g : Hom a b} → Limit (Fork {C = C} f g) → Equaliser C f g
I'm concerned about moving the functor to `Limit`. It's not the case that every functor from the parallel pair is a Fork definitionally, whereas the old type applied to any functor

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Finite.lagda.md
> +      equalisers : has-equalisers C
Win!

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Limit/Pullback.lagda.md
> +  → {F : Functor (·→·←· {x} {y}) Cat}
I love how we have a category called 👉👈 (edit: don't mind me, I'm just tired)

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Monad/Limits.lagda.md
> +  Forget-lift-limit : Limit (Forget C M F∘ F) → Limit F
Can this have more comments?

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Monad/Limits.lagda.md
> +  Forget-lift-limit : Limit (Forget C M F∘ F) → Limit F
Also, research question: is this an instance of a more general fact about Kan extensions?

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Product.lagda.md
> +  swap = ⟨ π₂ , π₁ ⟩
Great changes in this module all around

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Product.lagda.md
> +module BinaryProducts (all-products : has-products) where
`Binary-products` though

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Product/Indexed.lagda.md
> +        ip.unique eta q
These don't need to be broken up like this. Also in the indexed coproduct module

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Adjoint/Continuous.lagda.md
> +We now show that adjoint functors preserve "concrete limits". We could
Yup, good change

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Adjoint/Kan.lagda.md
> +[right adjoints preserve limits]: Cat.Functor.Adjoint.Continuous.html
Maybe we should link to a _different_ proof, since our proof of rapl just links back here

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Dense.lagda.md
> +  dense-cone d .is-natural _ _ f = f .sq
This is a cocone, surely?

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Hom/Cocompletion.lagda.md
>  ```agda
More comments!

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Hom/Cocompletion.lagda.md
> +  lan : Lan (よ C) F
comments here too!

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Adjoint.lagda.md
> +[TODO: Reed M, 05/02/2023] Finish this!
[TODO: Reed M, 05/02/2023] Finish this!

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Duality.lagda.md
> +<!-- [TODO: Reed M, 05/02/2023] Opposite direction of duality. -->
[TODO: Reed M, 05/02/2023] Opposite direction of duality.

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Nerve.lagda.md
> +embedding.
This deserves a diagram

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Nerve.lagda.md
> +      Nat-path λ _ → funext λ _ → F.F-∘ _ _
I think this is an interesting definition, could we comment on it?

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Nerve.lagda.md
> +<summary>
```suggestion
<summary>

```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Nerve.lagda.md
> +    adj : Realisation F cocompl ⊣ Nerve F
It's nice that the proof is shorter but I'm a bit miffed about having lost that paragraph describing the unit and counit

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Pointwise.lagda.md
> +# Pointwise Kan Extensions
Comment here

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Pointwise.lagda.md
> +```agda
Nasty construction definitely needs comments

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Functor/Kan/Pointwise.lagda.md
> +```agda
Even more comments here

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Instances/Functor/Limits.lagda.md
> +    functor-apex : Functor E C
This is a lot shorter but it needs comments too

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Instances/Shape/Initial.lagda.md
> +This category is notable, as there exists a unique functor from
```suggestion
This category is notable for the existence of a unique functor from
```

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Reasoning.lagda.md
> +  intro-inner : f ∘ g ≡ f ∘ a ∘ g
Maybe not those letters LMAO

2023-02-24 04:44 UTC, plt-amy commented on src/Cat/Diagram/Coproduct/Indexed.lagda.md
> +        ic.unique eta q
I left a comment on the indexed product module too but these could be on the same line

2023-02-24 19:42 UTC, TOTBWF commented on src/Cat/Abelian/Base.lagda.md
> +morphisms and the factors property of the product to establish the
whoops 🙃

2023-02-24 20:28 UTC, TOTBWF commented on src/Cat/Diagram/Coend/Formula.lagda.md
> +    ∙ (sym $ eta .is-natural _ _ (twist _ _ (C.cancelr (C.idl _))))
I can resurrect it; was just trying to get things to compile at this point

2023-02-24 20:29 UTC, plt-amy commented on src/Cat/Diagram/Coend/Formula.lagda.md
> +    ∙ (sym $ eta .is-natural _ _ (twist _ _ (C.cancelr (C.idl _))))
love me some necromancy

2023-02-24 20:35 UTC, TOTBWF commented on src/Cat/Functor/Adjoint/Kan.lagda.md
> +[right adjoints preserve limits]: Cat.Functor.Adjoint.Continuous.html
Lmao yeah that's a good call

2023-02-24 20:39 UTC, TOTBWF commented on src/Cat/Reasoning.lagda.md
> +  intro-inner : f ∘ g ≡ f ∘ a ∘ g
😬

2023-02-24 20:40 UTC, TOTBWF commented on support/nix/build-shake.nix
> -  upx ${main}
This is required to get things working on OSX with nix

2023-02-25 16:50 UTC, TOTBWF commented on src/Cat/Diagram/Colimit/Base.lagda.md
> +# Uniqueness
Done!

2023-02-25 17:33 UTC, TOTBWF commented on src/Cat/Diagram/Coproduct/Indexed.lagda.md
> +    → is-lan !F (Disc-adjunct F) K eps
No, `eps` isn't derived from `cocone→unit cocone` so this is slightly more general.

2023-02-25 19:11 UTC, TOTBWF commented on src/Cat/Diagram/Duals.lagda.md
> +  Colimit→Co-limit colim = to-limit (to-is-limit ml) where
Unfortunately, proof assistants. `Functor.op !F` is not defeq to `!F`, so it's less tedious to do it this way.

2023-02-25 23:44 UTC, ncfavier commented on src/Cat/Diagram/Monad/Limits.lagda.md
> +  Forget-lift-limit : Limit (Forget C M F∘ F) → Limit F
[Certainly looks like it!](https://github.com/ncfavier/1lab/commit/1950658dce72591d30b1a22f2a590b8067d3b54b#diff-6d00dd9cd17f3a9a0daf92792d2beb98ccfc28e8f381ec8dcb6adb04eebd96bf) The remaining holes should be pretty straightforward, but I'm done for today.

Natural transformations are *really annoying* to work with, but maybe I just don't know how (transports don't seem to compute?)

2023-03-21 16:32 UTC, plt-amy submitted a review, later dismissed

2023-03-21 17:02 UTC, merged