Internal sums of displayed categories
plt-amy/1lab pull request #204
Opened 2023-04-12 12:10 UTC by Daniel-Soe

# Description

This PR defines internal sums of displayed categories. To make this definition I added the composition of displayed functors, displayed functors over a single base, displayed natural transformation and displayed adjoints. 

## Checklist

Before submitting a merge request, please check the items below:

- [x] The imports are sorted (use `find -type f -name \*.agda -or -name \*.lagda.md | xargs support/sort-imports.hs`)

- [x] All code blocks have "agda" as their language. This is so that
tools like Tokei can report accurate line counts for proofs vs. text.

- [x] Proofs are explained to a satisfactory degree; This is subjective,
of course, but proofs should be comprehensible to a hypothetical human
whose knowledge is limited to a working understanding of non-cubical
Agda, and the stuff your pages link to.

The following items are encouraged, but optional:

- [ ] If you feel comfortable, add yourself to the Authors page! Add a
profile picture that's recognisably "you" under support/pfps; The
picture should be recognisable at 128x128px, should look good in a
squircle, and shouldn't be more than 200KiB.

- [ ] If your contribution makes mention of a negative statement, but
does not prove the negative (perhaps because it would distract from the
main point), consider adding it to the counterexamples folder.

- [ ] If a proof can be done in both "cubical style", and "book HoTT
style", and you have the energy to do both, consider doing both!
However, it is **completely fine** to only do one! For instance, I
(Amélia) am much better at writing proofs "book-style".

If a commit affects many files without adding any content and you don't
want your name to appear on those pages (for example, treewide refactorings
or reformattings), start the commit message with `chore:` or include the word
`NOAUTHOR` anywhere.

2023-04-19 14:44 UTC, plt-amy commented
@TOTBWF can you review the maths in this?

2023-04-19 18:13 UTC, TOTBWF requested changes
First of all, thank you so much! I do have some minor naming/prose suggestions though, as well as one larger question about the math.

It is somewhat surprising to me that we are able to define internal sums even when `E` is not a fibration; the definition I'm familiar with requires left adjoints to reindexing + Beck Chevalley. Furthermore, I'm surprised you don't even need pullbacks in `B`. I do wonder if something goes wrong when `E` is a fibration yet `B` lacks pullbacks; I can't think of anything off the top of my head, but it's something to ponder.

2023-04-19 18:13 UTC, TOTBWF commented on src/Cat/Displayed/NaturalTransformation.lagda.md
> +$\bf{\eta} : \bf{F} \To \bf{G}$ is called **cartesian** if
We should call these "vertical natural transformations" IMO.

2023-04-19 18:13 UTC, TOTBWF commented on src/Cat/Displayed/NaturalTransformation.lagda.md
> +      is-natural : ∀ {x y f} (x′ : ℰ.Ob[ x ]) (y′ : ℰ.Ob[ y ]) (f′ : ℰ.Hom[ f ] x′ y′)
```suggestion
      is-natural′ : ∀ {x y f} (x′ : ℰ.Ob[ x ]) (y′ : ℰ.Ob[ y ]) (f′ : ℰ.Hom[ f ] x′ y′)
```

2023-04-19 18:13 UTC, TOTBWF commented on src/Cat/Displayed/NaturalTransformation.lagda.md
> +      is-natural : ∀ {x y f} (x′ : ℰ.Ob[ x ]) (y′ : ℰ.Ob[ y ]) (f′ : ℰ.Hom[ f ] x′ y′)
```suggestion
      is-natural′ : ∀ {x y f} (x′ : ℰ.Ob[ x ]) (y′ : ℰ.Ob[ y ]) (f′ : ℰ.Hom[ f ] x′ y′)
```

2023-04-20 20:03 UTC, TOTBWF commented
I actually need a lot of this code for some things I'm working on (Fibred Limits + Colimits); do you mind if I make some changes on this branch to get it merged quickly?

2023-04-20 20:33 UTC, Daniel-Soe commented
@TOTBWF thank you for taking your time an reviewing my code. 

You are right, most literature defines internal sums only for a fibration $E$, but I never needed this assumption on $E$ so I dropped it.
For the case that $E$ is a fibration we need additionally that $B$ has pullbacks to prove that the codomain functor is a fibration which is needed to show that the family of $E$ `FamDisp` ist a fibration. 

I made all your requested changes except for the renaming, waiting for the response of @plt-amy. Now you can change whatever you want.

2023-04-20 20:46 UTC, TOTBWF commented
Thanks so much!

P.S: When did github add $\LaTeX$!?

2023-04-20 20:59 UTC, Daniel-Soe commented
> P.S: When did github add LATEX!?

I don't know, this was my first github comment and I just hoped that it would work😁

2023-04-21 02:40 UTC, TOTBWF commented
Did some reorganizing and wrote some prose, but the code you gave was excellent! Thank you very much 🙂

2023-04-21 16:02 UTC, TOTBWF approved these changes

2023-04-21 17:50 UTC, merged