Equivalence facts
plt-amy/1lab pull request #240
Opened 2023-07-17 18:03 UTC by TOTBWF

# Description

Some misc. properties of various classes of morphisms, along with some properties of equivalences.

2023-07-25 23:10 UTC, plt-amy requested changes

2023-07-25 23:10 UTC, plt-amy commented on src/1Lab/Equiv.lagda.md
> +Lift-path = Lift-pathp refl
Is there any case where this would be better than `ap lift`?

2023-07-25 23:10 UTC, plt-amy commented on src/Cat/Functor/Base.lagda.md
> +A functor $F : \cC \to \cD$ is an equivalence on objects if it's action
its

2023-07-25 23:10 UTC, plt-amy commented on src/Cat/Functor/Base.lagda.md
> +on objects is an equivalence (shocking!).
drop the sarcasm

2023-07-25 23:10 UTC, plt-amy commented on src/Cat/Functor/Base.lagda.md
> +A functor $F : \cC \to \cD$ is an equivalence on objects if it's action
also "equivalence on objects" should be bold

2023-07-25 23:17 UTC, TOTBWF commented on src/1Lab/Equiv.lagda.md
> +Lift-path = Lift-pathp refl
I think I was on autopilot here, whoops!

2023-07-28 20:00 UTC, plt-amy approved these changes

2023-07-28 20:00 UTC, merged