Restriction categories
plt-amy/1lab pull request #247
Opened 2023-08-05 19:02 UTC by TOTBWF

This PR defines [restriction categories](https://ncatlab.org/nlab/show/restriction+category), and proves that every allegory has a restriction structure on it's category of partial maps.

2023-08-05 19:03 UTC, plt-amy commented
> it's category of partial maps

:pensive:

2023-08-05 19:04 UTC, TOTBWF commented
> > it's category of partial maps
> 
> 😔

I did a grammar check, yet I missed the PR description 🙃

2023-08-06 02:58 UTC, plt-amy requested changes

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Allegory/Morphism.lagda.md
> +As coreflexive morphisms are both transitive and cotransitive, they
Can you make this
```
transitive ($f \le ff^o$)
```
same for cotransitive, and mention antisymmetry?

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Allegory/Morphism.lagda.md
> +```
Can you add some prose explaining how this condition works out in Rel?

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Allegory/Morphism.lagda.md
> +functional-∩ : is-functional f → is-functional g → is-functional (f ∩ g)
Is there space betweev the cap, the colon, and the i?

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Allegory/Morphism.lagda.md
> +```
Same thing about explaining in Rel here

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Allegory/Morphism.lagda.md
> +The domain of an entire morphism is identity.
the identity

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Base.lagda.md
> +we constantly find ourselves incurring proof obligations, which
what obligations?

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Base.lagda.md
> +$A \to \rm{Maybe}(B)$. **Restriction categories** aim to ease this burden
Can you add an explanation for why? Could be a footnote.

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Base.lagda.md
> +that maps $x$ to itself if $f(x)$ is defined, and diverges otherwise.
Can you make this "maps x to itself iff f(x) is defined"? The LEM wording doesn't really fit imo

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Base.lagda.md
> +We require that $(-)\downarrow$ satisfies 4 axioms:
IMO merge this list with the one below, and put each axiom-code-block under the corresponding list item

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Functor.lagda.md
> +A functor $F : \cC \to \cD$ is a **restriction functor** if
a functor $...$ between _restriction categories_ - with a link!

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Instances/Allegory.lagda.md
> +morphisms instead of functional _and_ [entire] relations.
choose either morphism or relation

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Instances/Allegory.lagda.md
> +This category can be equipped with a restriction structure by taking
"a restriction structure, defining $f\downarrow$ to be the [domain] of $f$"

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Instances/Allegory.lagda.md
> +actually require functionality; it's only the reverse direction of
~~functionality~~ the relation to be functional

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Instances/Allegory.lagda.md
> +actually require functionality; it's only the reverse direction of
"it's only relevant in the converse direction of the 4th axiom"

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Reasoning.lagda.md
> +$g, h : A \to X$, $f \circ g = f \circ h$ implies that
I would drop the \circs

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Reasoning.lagda.md
> +Let $r : X \to Y$ and $s : Y \to X$ be a pair of morphisms. $r$ is a
The map $r$ — don't start sentences with maths

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Reasoning.lagda.md
> +**restricted retract** of $s$ when $r \circ s = s \downarrow$.
ditto \circ

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Reasoning.lagda.md
> +If $f$ and $g$ have restricted retracts, then so does $f \circ g$.
ditto \circ

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Reasoning.lagda.md
> +If $f \circ g$ has a restricted retract and $f$ is total, then $g$ has a restricted
ditto \circ

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Reasoning.lagda.md
> +are **restricted inverses** if $f \circ g = g \downarrow$ and
ditto \circ

2023-08-06 02:58 UTC, plt-amy commented on src/Cat/Restriction/Reasoning.lagda.md
> +$g$ refines $f$ if $g$ agrees with $f$ when restricted to the domain of
**refines**

2023-08-06 02:58 UTC, plt-amy commented on src/index.lagda.md
> +an restriction operation $(-)\downarrow : \cC(X,Y) \to \cC(X,X)$ that
a

2023-08-06 04:20 UTC, TOTBWF commented on src/Cat/Allegory/Morphism.lagda.md
> +functional-∩ : is-functional f → is-functional g → is-functional (f ∩ g)
I'm not quite sure I follow!

2023-08-06 06:32 UTC, plt-amy commented on src/Cat/Allegory/Morphism.lagda.md
> +functional-∩ : is-functional f → is-functional g → is-functional (f ∩ g)
Was just my browser being silly, nvm

2023-08-06 06:32 UTC, plt-amy approved these changes

2023-08-06 06:32 UTC, merged