Concrete groups
plt-amy/1lab pull request #254
Opened 2023-08-27 16:24 UTC by ncfavier

Defines connectedness, concrete groups (pointed connected groupoids), and an equivalence between the categories of concrete and abstract (set-based) groups.

The section on delooping homomorphisms is largely inspired by [[Symmetry](https://unimath.github.io/SymmetryBook/book.pdf) §4.10], which was apparently written by Thierry Coquand(?).

I'm not sure how to best organise concepts into modules in a way that avoids cyclic dependencies. If you have any ideas at all, please advise. Currently things are kind of strewn about between `1Lab.Type.Pointed`, `1Lab.Connectedness`, `Algebra.Group.Homotopy`, `Homotopy.Base`, and now `Algebra.Group.Concrete`, with all sorts of 🐔🔄🥚 problems lurking around the corner.

[Rendered](https://1lab-concrete-groups.monade.li/Algebra.Group.Concrete.html)

## Checklist

Before submitting a merge request, please check the items below:

- [X] The imports are sorted (use `find -type f -name \*.agda -or -name \*.lagda.md | xargs support/sort-imports.hs`)

- [X] All code blocks have "agda" as their language. This is so that
tools like Tokei can report accurate line counts for proofs vs. text.

- [X] Proofs are explained to a satisfactory degree; This is subjective,
of course, but proofs should be comprehensible to a hypothetical human
whose knowledge is limited to a working understanding of non-cubical
Agda, and the stuff your pages link to.

The following items are encouraged, but optional:

- [ ] If you feel comfortable, add yourself to the Authors page! Add a
profile picture that's recognisably "you" under support/pfps; The
picture should be recognisable at 128x128px, should look good in a
squircle, and shouldn't be more than 200KiB.

- [ ] If your contribution makes mention of a negative statement, but
does not prove the negative (perhaps because it would distract from the
main point), consider adding it to the counterexamples folder.

- [ ] If a proof can be done in both "cubical style", and "book HoTT
style", and you have the energy to do both, consider doing both!
However, it is **completely fine** to only do one! For instance, I
(Amélia) am much better at writing proofs "book-style".

If a commit affects many files without adding any content and you don't
want your name to appear on those pages (for example, treewide refactorings
or reformattings), start the commit message with `chore:` or include the word
`NOAUTHOR` anywhere.

2023-09-04 11:42 UTC, plt-amy requested changes

2023-09-04 11:42 UTC, plt-amy commented on src/1Lab/Connectedness.lagda.md
> +is-n-2-connected : ∀ {ℓ} → Type ℓ → Nat → Type _
not a fan of this name: "is n 2 connected?"

2023-09-04 11:42 UTC, plt-amy commented on src/1Lab/Connectedness.lagda.md
> +S¹-is-connected : is-connected∙ (S¹ , base)
Keep the textual references but cut the code, no imports from 1Lab.* to the outside

2023-09-04 11:42 UTC, plt-amy commented on src/1Lab/Connectedness.lagda.md
> +module 1Lab.Connectedness where
this should be in Homotopy.* imo

2023-09-04 11:42 UTC, plt-amy commented on src/1Lab/Reflection/HLevel.agda
> +  {-
this change will be really bad for performance

2023-09-04 11:42 UTC, plt-amy commented on src/Algebra/Group/Concrete.lagda.md
> +```agda
this can also be in the comment

2023-09-04 11:42 UTC, plt-amy commented on src/Algebra/Group/Concrete.lagda.md
> +need since we're dealing with groupoids: loops already form a set.
"each loop space is already a set" instead?

2023-09-04 11:54 UTC, ncfavier commented on src/1Lab/Connectedness.lagda.md
> +S¹-is-connected : is-connected∙ (S¹ , base)
This is part of the organisation problem I was alluding to: I need to import stuff from the outside to even define connectedness, since n-truncations are in `Homotopy.Base`.

Maybe the module should be named `Homotopy.Connectedness` instead?

I've also thought about separating the definition of (0-)connectedness (which only requires stuff in `1Lab.*`) from the definition of n-connectedness, but that feels ugly...

2023-09-04 12:26 UTC, ncfavier commented on src/1Lab/Reflection/HLevel.agda
> +  {-
In that case I can uncomment Π² and Π³ and add instances for the "odd Π" h-level goals.

Out of curiosity, do you mean performance of the tactic itself, or of the generated terms?

2023-09-04 12:39 UTC, plt-amy commented on src/1Lab/Reflection/HLevel.agda
> +  {-
the tactic. if anything is reducing the generated terms it's probably a bug

2023-09-04 21:12 UTC, plt-amy approved these changes

2023-09-04 21:12 UTC, plt-amy commented on src/Authors.lagda.md
> -Test: [[displayed over|displayed category]]
lmao

2023-09-04 21:12 UTC, plt-amy commented on src/Authors.lagda.md
> +<div class="profile pfp-right">
Finally 😉

2023-09-04 21:13 UTC, merged

2023-09-04 21:15 UTC, ncfavier commented
Thanks!

2023-12-26 16:29 UTC, plt-amy commented on src/Algebra/Group/Concrete.lagda.md
> +  mk .idl = ∙-id-l
I think that was added in #271

2023-12-26 16:31 UTC, ncfavier commented on src/Algebra/Group/Concrete.lagda.md
> +  mk .idl = ∙-id-l
Oh yeah. I'll unify the two in my next PR