Extension systems + Relative Extension systems
plt-amy/1lab pull request #342
Opened 2024-01-13 15:43 UTC by TOTBWF

# Description

This PR defines extension systems and relative extension systems, and proves their equivalence with monads.

## Checklist

Before submitting a merge request, please check the items below:

- [x] I've read [the contributing guidelines](https://github.com/plt-amy/1lab/blob/main/CONTRIBUTING.md).
- [x] The imports of new modules have been sorted with `support/sort-imports.hs` (or `nix run --experimental-features nix-command -f . sort-imports`).
- [x] All new code blocks have "agda" as their language.

If your change affects many files without adding substantial content, and
you don't want your name to appear on those pages (for example, treewide
refactorings or reformattings), start the commit message and PR title with `chore:`.

2024-01-13 15:53 UTC, Lavenza commented
[Pull request preview](https://preview.1lab.dev/342)

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Relative.lagda.md
> +longer an endofunctor $\Sets \to \Sets$, and restricting $T$ to
```suggestion
longer be an endofunctor $\Sets \to \Sets$, and restricting $T$ to
```

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Relative.lagda.md
> +cannot iterate a functor $M : \cJ \to \cC$, so themost natural starting
```suggestion
cannot iterate a functor $M : \cJ \to \cC$, so the most natural starting
```

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Relative.lagda.md
> +extension, resp.
```suggestion
extension, respectively.
```

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Extension.lagda.md
> +We impose 3 additional equations atop this structure[^contrast this with
```suggestion
We impose 3 additional equations atop this structure^[contrast this with
```

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Extension.lagda.md
> +and extension algebras whenever it is convenient.
```suggestion
and extension systems whenever it is convenient.
```

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Extension.lagda.md
> +$\nu(id_{X}) : \cC(M(X), X)$.
```suggestion
$\nu(\id{X}) : \cC(M(X), X)$.
```

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Extension.lagda.md
> +$id_{M(X)} : \cC(M(X), M(X))$.
```suggestion
$\id{M(X)} : \cC(M(X), M(X))$.
```

2024-01-13 16:22 UTC, ncfavier commented on src/Cat/Diagram/Monad/Extension.lagda.md
> +1. For every $X : \cC$, $(\eta_X)^M = id_{M(X)}$
```suggestion
1. For every $X : \cC$, $(\eta_X)^M = \id{M(X)}$
```

2024-01-18 22:20 UTC, plt-amy requested changes
Sadly GitHub won't let me submit my review as [a patch](https://gist.github.com/plt-amy/6115e2a92facb4a7ee54239e962e7bb4).

2024-01-19 10:20 UTC, ncfavier commented on src/Cat/Diagram/Monad.lagda.md
> +```
```suggestion
```agda
```

2024-01-19 10:20 UTC, ncfavier commented on src/Cat/Diagram/Monad/Extension.lagda.md
> +```
```suggestion
```agda
```

2024-01-19 10:21 UTC, ncfavier approved these changes

2024-01-19 10:22 UTC, ncfavier commented
I'm going to guess the auto-merge wasn't intentional given the timing and disable it, but this might as well be merged as far as I'm concerned.

2024-01-19 10:25 UTC, ncfavier commented on src/Cat/Diagram/Monad/Extension.lagda.md
> +# Extension Systems {defines=extension-system}
```suggestion
# Extension systems {defines=extension-system}
```

2024-01-19 10:25 UTC, ncfavier approved these changes

2024-01-20 22:41 UTC, TOTBWF commented
I think we need @plt-amy to sign off to appease CI

2024-01-20 23:23 UTC, plt-amy approved these changes

2024-01-20 23:48 UTC, merged