wip: start writing new index
plt-amy/1lab pull request #346
Opened 2024-01-19 17:39 UTC by plt-amy

I'll be honest, it feels barren and I have no idea what to put there.

2024-01-19 17:48 UTC, Lavenza commented
[Pull request preview](https://preview.1lab.dev/346)

2024-01-19 20:14 UTC, ncfavier reviewed
Looks great! Here's what I think is missing so far:

- a word or two on the foundations we use (homotopy type theory, cubical Agda)
- some sort of broad description of the kind of mathematics we have (e.g. you'll find tons of category theory, not so much complex analysis), maybe give a quick tour of the top-level module namespaces like we had in the old index
- hint at the "all pages" button, which is kind of hidden in the UI

2024-01-19 20:14 UTC, ncfavier commented on support/web/css/code.scss
> +  overflow-y: scroll;
Why this change? The added scrollbars are kind of ugly.

![screenshot-2024-01-19-210552](https://github.com/plt-amy/1lab/assets/4323933/b4a96013-6591-4260-976c-21bd668a5c08)

2024-01-19 20:56 UTC, ncfavier commented on support/web/css/code.scss
> +  overflow-y: scroll;
Some math blocks are still getting scrollbars:

![screenshot-2024-01-19-215542](https://github.com/plt-amy/1lab/assets/4323933/9b62ac1f-6677-45da-834f-3a497a417ad5)

2024-01-19 21:07 UTC, plt-amy commented on support/web/css/code.scss
> +  overflow-y: scroll;
okay now *that's* funky

2024-01-19 22:00 UTC, SquidDev requested changes
Just a couple of phrasing tweaks. Really like what you've done here :heart:.

2024-01-19 22:00 UTC, SquidDev commented on src/index.lagda.md
> +Making the formalisation explorable requires taking the Web-native
```suggestion
Making the formalisation explorable requires taking the web-native
```

2024-01-19 22:00 UTC, SquidDev commented on src/index.lagda.md
> +extensive library of formalised mathematics, presented as an explorable
I think it's good that we're being more broad about what the 1Lab formalises, but I do think it's worth mentioning the cubical nature of the formalisation early on, somewhere in the first few sentences?

2024-01-19 22:00 UTC, SquidDev commented on src/index.lagda.md
> +  prefix; it's only displayed so you know where you'll be taken.
Everywhere else we refer to "the reader", but here uses "you". We should probably use "the reader" here too.

2024-01-19 22:00 UTC, SquidDev commented on src/index.lagda.md
> +by searching for their name in the book.
```suggestion
that this page is also indexed for search, so you can find a definition
by searching for its name in the book.
```

2024-01-19 22:00 UTC, SquidDev commented on src/index.lagda.md
> +it is first and foremost a community project. The literal work takes
Maybe "practical work"? Or "the formalisation"? "literal" is a bit ... messy.

2024-01-19 22:00 UTC, SquidDev commented on src/index.lagda.md
> +::: {#recent-additions}
Oooooh, this is snazzy.

2024-01-19 22:00 UTC, SquidDev commented on src/index.lagda.md
> +believe HoTT is for everyone and are committed to fostering a kind,
"We believe" makes the statement less strong.

```suggestion
background, ethnicity, gender identity, or gender expression. **HoTT
is for everyone and are committed to fostering a kind,
```

2024-01-19 22:45 UTC, ncfavier commented on src/index.lagda.md
> +  prefix; it's only displayed so you know where you'll be taken.
I see more "you"s than "reader"s, and I think "you" is more natural.

2024-01-26 18:24 UTC, plt-amy commented on src/index.lagda.md
> +  prefix; it's only displayed so you know where you'll be taken.
Both times "reader" shows up it's in the construction _each reader_, though. I don't think there's a change to be made here

2024-02-21 15:57 UTC, ncfavier submitted a review, later dismissed

2024-02-22 12:17 UTC, merged