wording: dust off 1Lab.Path
plt-amy/1lab pull request #379
Opened 2024-05-29 19:24 UTC by plt-amy

Pretty major cleanup of the wording in 1Lab.Path, incorporating some feedback I got recently (and trying to fit the prose to the code and vice-versa).

2024-05-29 19:38 UTC, Lavenza commented
[Pull request preview](https://preview.1lab.dev/379)

2024-05-30 06:24 UTC, LiamGoodacre commented on src/1Lab/Path.lagda.md
> +horizontal direction.
`drop-i` -> `drop-j`?

2024-05-30 16:27 UTC, plt-amy commented on src/1Lab/Path.lagda.md
> +horizontal direction.
Yep, thank you!

2024-05-30 17:15 UTC, SquidDev reviewed
Sorry, only a quarter of the way through, but didn't feel worth holding on to this until the end.

2024-05-30 17:38 UTC, plt-amy commented on src/1Lab/Path.lagda.md
> +of *paths* $a \is b$ in $A$. There is a constant path $\refl : a
Does

> if we interpret a type $A$ as a space, then for a pair of points $a, b : A$, the identity type $a \equiv b$ behaves like the space of *paths*, from $a$ to $b$, in $A$.

read better?

2024-05-30 22:19 UTC, SquidDev reviewed
Sorry, really taking my time on going through this. This definitely feels like an improvement though, I definitely feel like I'm grokking it much better.

2024-05-30 22:19 UTC, SquidDev commented on src/1Lab/Path.lagda.md
> +[[connections]]. We're given an inhabitant $y : A$ and a path $p : x \is
This is the first time "boundaries" and "connections" appears on the page. The linked functions are called `-conn`, but maybe could be clearer?

2024-05-30 22:19 UTC, SquidDev commented on src/1Lab/Path.lagda.md
> -Singleton-is-contr {x = x} (y , path) i = path i , square i where
Is there a reason to use the long-form `Path` here instead of $\equiv$? Is this just to make the `Singleton x` type explicit?

2024-05-30 22:19 UTC, SquidDev commented on src/1Lab/Path.lagda.md
> +  in λ i → p i , snds i
I think this is the first practical use of `Square`, so I'd be inclined to hold the hand a little more here.

I ended up drawing out the square out for this, and working through the two endpoints to see what was going on. I think it's actually very obvious when written out (and honestly, maybe the reader *should*, just so they can sort of check their own understanding).


<details><summary>Notes I made</summary>

```
x y : A
p : x = y

     refl
   x ---- x
re |      | p
fl |      |
   x ---- y
      p

f i0 = (p i0, snds i0) = (x, refl)
f i1 = (p i0, snds i1) = (y, p)
```

</details>

2024-05-30 22:22 UTC, plt-amy commented on src/1Lab/Path.lagda.md
> -Singleton-is-contr {x = x} (y , path) i = path i , square i where
Yeah, Agda can't infer what `Σ` type the pairs live in otherwise

2024-05-31 19:18 UTC, SquidDev reviewed
One minor thing on the remaining half, but otherwise :+1:

2024-06-06 10:44 UTC, ncfavier commented on src/1Lab/Path.lagda.md
> +has to be free: if it weren't, our path might get snagged on something!
💜💜💜

2024-06-06 10:44 UTC, ncfavier commented on src/1Lab/Path.lagda.md
> -[Intro to HoTT](1Lab.intro.html) page.
Is the intro even linked from anywhere now? 😆

2024-06-06 16:27 UTC, plt-amy commented on src/1Lab/Path.lagda.md
> -[Intro to HoTT](1Lab.intro.html) page.
no, i'm preparing to get rid of it.

2024-06-06 18:30 UTC, SquidDev requested changes

2024-06-06 18:30 UTC, SquidDev commented on src/1Lab/Path.lagda.md
>  $$,
Sorry, didn't notice this the first time round, but I find it a bit odd how this one is a math block, but the next is inline. Might be a little better if the next paragraph read "Similarly, the right face in ..."?

2024-06-06 18:30 UTC, SquidDev commented on src/1Lab/Path.lagda.md
> +of a complete 2-dimensional *square*: this can be defined in terms of
```suggestion
of a complete 2-dimensional *square*. This can be defined in terms of
```

2024-06-06 18:30 UTC, SquidDev commented on src/1Lab/Path.lagda.md
> +is read as saying that the *composites* $q \cdot r$ and $p \cdot s$ are
I think it's probably better to start a new sentence here, rather than continuing the one before the diagram.

2024-06-06 18:30 UTC, SquidDev commented on src/1Lab/Path.lagda.md
> +## The need for hcomp
:heart_eyes: Thank you!

2024-06-06 19:55 UTC, SquidDev approved these changes
:shipit:

2024-06-06 19:55 UTC, merged